#!/usr/bin/env bash
# Load / save deploy.config and gather connection settings interactively.

DEPLOY_CONFIG_FILE="${DEPLOY_ROOT}/deploy.config"

# Defaults (overridden by deploy.config / prompts)
DEPLOY_HOST="${DEPLOY_HOST:-104.248.224.133}"
DEPLOY_USER="${DEPLOY_USER:-root}"
DEPLOY_SSH_KEY="${DEPLOY_SSH_KEY:-$HOME/.ssh/id_ed25519}"
DEPLOY_SSH_ALIAS="${DEPLOY_SSH_ALIAS:-portfolio-deploy}"
DEPLOY_REMOTE_DIR="${DEPLOY_REMOTE_DIR:-/opt/portfolio_v3}"
DEPLOY_DOMAIN="${DEPLOY_DOMAIN:-}"
DEPLOY_APP_PORT="${DEPLOY_APP_PORT:-8472}"
DEPLOY_GIT_URL="${DEPLOY_GIT_URL:-https://github.com/arnoldchrisoduor1/portfolio_v3.git}"
DEPLOY_BRANCH="${DEPLOY_BRANCH:-main}"
DEPLOY_SITE_NAME="${DEPLOY_SITE_NAME:-portfolio_v3}"
DEPLOY_PUBLIC_URL="${DEPLOY_PUBLIC_URL:-}"

config_load() {
  if [[ -f "$DEPLOY_CONFIG_FILE" ]]; then
    # shellcheck disable=SC1090
    source "$DEPLOY_CONFIG_FILE"
  fi
  # Recompute public URL if still empty
  if [[ -z "${DEPLOY_PUBLIC_URL:-}" ]]; then
    if [[ -n "${DEPLOY_DOMAIN:-}" ]]; then
      DEPLOY_PUBLIC_URL="https://${DEPLOY_DOMAIN}"
    else
      DEPLOY_PUBLIC_URL="http://${DEPLOY_HOST}"
    fi
  fi
}

config_save() {
  cat >"$DEPLOY_CONFIG_FILE" <<EOF
# Generated by deploy.sh — local only (gitignored)
DEPLOY_HOST='${DEPLOY_HOST}'
DEPLOY_USER='${DEPLOY_USER}'
DEPLOY_SSH_KEY='${DEPLOY_SSH_KEY}'
DEPLOY_SSH_ALIAS='${DEPLOY_SSH_ALIAS}'
DEPLOY_REMOTE_DIR='${DEPLOY_REMOTE_DIR}'
DEPLOY_DOMAIN='${DEPLOY_DOMAIN}'
DEPLOY_APP_PORT='${DEPLOY_APP_PORT}'
DEPLOY_GIT_URL='${DEPLOY_GIT_URL}'
DEPLOY_BRANCH='${DEPLOY_BRANCH}'
DEPLOY_SITE_NAME='${DEPLOY_SITE_NAME}'
DEPLOY_PUBLIC_URL='${DEPLOY_PUBLIC_URL}'
EOF
  change_record "[saved]     deploy.config → ${DEPLOY_HOST} (${DEPLOY_USER})"
  log_ok "Saved ${DEPLOY_CONFIG_FILE}"
}

# Interactive (or reuse-saved) config collection.
config_ensure() {
  config_load

  if [[ -f "$DEPLOY_CONFIG_FILE" ]]; then
    log_info "Found saved config: ${DEPLOY_USER}@${DEPLOY_HOST}  key=${DEPLOY_SSH_KEY}"
    if ui_confirm "Use saved server config?" Y; then
      config_load
      return 0
    fi
  fi

  ui_section "Server connection"
  DEPLOY_HOST="$(ui_ask "Server host/IP" "$DEPLOY_HOST")"
  DEPLOY_USER="$(ui_ask "SSH user" "$DEPLOY_USER")"
  DEPLOY_SSH_KEY="$(ui_ask "SSH private key path" "$DEPLOY_SSH_KEY")"
  DEPLOY_SSH_ALIAS="$(ui_ask "SSH config alias" "$DEPLOY_SSH_ALIAS")"
  DEPLOY_REMOTE_DIR="$(ui_ask "Remote project directory" "$DEPLOY_REMOTE_DIR")"
  DEPLOY_DOMAIN="$(ui_ask "Domain (blank = use IP / skip SSL)" "${DEPLOY_DOMAIN}")"
  DEPLOY_APP_PORT="$(ui_ask "Container host port" "$DEPLOY_APP_PORT")"
  DEPLOY_GIT_URL="$(ui_ask "Git clone URL" "$DEPLOY_GIT_URL")"
  DEPLOY_BRANCH="$(ui_ask "Git branch" "$DEPLOY_BRANCH")"

  if [[ -n "$DEPLOY_DOMAIN" ]]; then
    DEPLOY_PUBLIC_URL="https://${DEPLOY_DOMAIN}"
  else
    DEPLOY_PUBLIC_URL="http://${DEPLOY_HOST}"
  fi
  DEPLOY_PUBLIC_URL="$(ui_ask "Public URL for reachability checks" "$DEPLOY_PUBLIC_URL")"

  if ui_confirm "Save this config to deploy.config?" Y; then
    config_save
  fi
}
